# Generated by Django 4.2.1 on 2023-06-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'verbose_name_plural': 'ChatMessages'},
        ),
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['-modified_on'], 'verbose_name_plural': 'Chats'},
        ),
    ]
