# Generated by Django 4.2.1 on 2023-06-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chatmessages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Chat Messages'},
        ),
    ]
